AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance in a specific Availability Zone
# this code is working in N. Virginia region and Ohio region, it didn't work for Stockholm
Parameters:
  InstanceType:
    Type: String
    # Default: t2.micro
    Description: EC2 instance type
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Specific Availability Zone to launch the EC2 instance (e.g., us-east-1a)
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: Amazon Machine Image (AMI) ID

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: 
        - !Ref AvailabilityZone
        - !Ref AvailabilityZone
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId

